### ISSUE TITLE
Lighten Python version requirement

### ISSUE THREAD

**Issue by mtache** [jeremyschulman/aio-eapi#9]
Hi Jeremy,

Thank you for this framework ! It works perfectly well with EOS.
We are actually using it on pure Python testing framework based on asyncio: https://github.com/arista-netdevops-community/anta

One issue is that we would like to bump aio-eapi version to the latest, taking benefits of the improvements you've done since 0.3.0, but the required Python version is 3.10. In reality, a lot of environment still runs Python 3.7-3.9 (especially when this is coupled with AVD).

We would like to avoid forking your work: would it be possible to lighten the Python version requirement to something like Python 3.8 (which is the current minimal Python version for ANTA) ?

Today, we live with this kind of patch in our code: https://github.com/arista-netdevops-community/anta/blob/master/anta/inventory/models.py#L35

**Comment by jeremyschulman** [comment]
@mtache - thank you for your note.  I will fix this no problem.

**Comment by jeremyschulman** [comment]
@mtache - I've uploaded the updated package to pypi as v0.6.1.  Please let me know if all is AOK on your end.  Thank you,

**Comment by mtache** [comment]
Thank you for the quick PR !

I get 2 TypeErrors with Python 3.9.16 and aio-eapi 0.6.1:

```
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/aioeapi/config_session.py", line 86, in SessionConfig
    async def status(self) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
```
  File "/home/mtache/.pyenv/versions/3.9.16/envs/anta/lib/python3.9/site-packages/aioeapi/config_session.py", line 135, in SessionConfig
    async def push(self, content: list[str] | str, replace: Optional[bool] = False):
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'
```

Besides this, it worked well. Thank you again

**Comment by jeremyschulman** [comment]
@mtache - if you would like to make a pull request with the needed updates that would be helpful.  I am traveling at the moment, and will be delayed for a few days otherwise. Thank you!

**Comment by mtache** [comment]
@jeremyschulman, I missed a list typing that is not working for Python 3.8, sorry !
I raised PR #12 with the updated line of code.
Thank you !
